---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 이민규.
--- DateTime: 24. 7. 10. 오후 5:02
---

function printHelloWorld()
    print("Hello world!!")
end

printHelloWorld()

function plus(x, y)
    return x + y
end

result = plus(2,3)
print(result)

function multiply(a,b)
    return a*b
end

result = multiply(2,3)
print(result)

--Lua에서는 함수 자체를 인자로 받을 수 있다.
function operating(oper, a, b)
    if oper == plus or oper == multiply then
        return oper(a,b)
    end
end

print(operating(plus, 2, 5))
print(operating(multiply, 2, 5))
