---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 이민규.
--- DateTime: 24. 7. 10. 오후 3:06
---

first = 5
second = '안녕'
third = true
fourth = {1,3,5,7}
fifth = {['asd'] = 1, ['def'] = 2, ['cva'] = 'asvs'}
sixth = nil --null값

print(first)
print(second)
print(third)
print(fourth) -- 테이블의 경우 그냥 출력하면 주소값 출력됨

-- 테이블의 값을 출력하기 위해서는 반복문을 돌릴 필요가 있음.
-- pairs의 경우 모든 요소를 임의의 순서로 반복함. 순서가 바뀔 수 있음.
for key, value in pairs(fourth) do
    print("테이블의", key, "번째 값", value)
end

-- ipairs의 경우 인덱스가 1부터 시작하는 순차적인 정수 키를 사용하여 테이블을 반복함.
for i, value in ipairs(fourth) do
    print("테이블의", i, "번째 값", value)
end

for i, value in ipairs(fourth) do
    io.write("테이블의 " .. i .. "번째 값 " .. value .. "\n")
end

for key, value in pairs(fifth) do
    print("테이블의 key값 = ", key, " value =", value)
end

-- 출력 안 됨
-- 정수 키가 없으므로, ipairs는 첫 번째 인덱스 (1)에서 nil을 찾고 즉시 종료되기 때문.
for i, value in ipairs(fifth) do
    print("테이블의 key값 = ", i, " value =", value)
end

print(sixth)